# Generated by Django 3.1.6 on 2021-02-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=120, unique=True)),
                ('manufacturer', models.CharField(max_length=120)),
                ('mobile_name', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=50)),
            ],
        ),
    ]
