# Generated by Django 3.1.6 on 2021-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_mobile_model_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=120)),
                ('buyer_address', models.TextField(max_length=500)),
                ('buyer_mobile', models.CharField(max_length=100)),
            ],
        ),
    ]
