# Generated by Django 3.1.6 on 2021-03-11 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0004_buyer_model_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_model',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobileapp.mobile_model'),
        ),
    ]
