# Generated by Django 3.1.6 on 2021-03-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0005_auto_20210311_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_model',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
