# Generated by Django 3.1.6 on 2021-03-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0006_buyer_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_model',
            name='product',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
