# Generated by Django 3.1.6 on 2021-03-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0009_auto_20210312_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_model',
            name='status',
        ),
    ]
