# Generated by Django 3.1.6 on 2021-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0010_remove_buyer_model_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='vieworder_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(max_length=120)),
            ],
        ),
    ]
