# Generated by Django 3.1.6 on 2021-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0011_vieworder_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_model',
            name='status',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
