# Generated by Django 3.1.6 on 2021-03-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0012_buyer_model_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vieworder_model',
        ),
    ]
